FROM ubuntu:16.04

RUN apt-get update && apt-get install -y netcat

COPY storytime /storytime

COPY libc.so.6 /lib/custom_libc/libc.so.6

COPY run.sh /run.sh

RUN chmod +x /storytime /lib/custom_libc/libc.so.6 run.sh

EXPOSE 12345

CMD ["nc", "-lvp", "12345", "-e", "/run.sh"]