FROM ubuntu:18.04

RUN dpkg --add-architecture i386

RUN apt-get update && apt-get install -y libc6:i386 socat

COPY flag.txt /flag.txt

COPY libc-2.27.so /lib/custom_libc/libc.so.6

COPY betstar5000 /server

COPY run.sh /run.sh

RUN chmod +x /server /lib/custom_libc/libc.so.6 run.sh

EXPOSE 5000

# CMD ["sh", "-c", "socat TCP-LISTEN:5000,reuseaddr,fork EXEC:/run.sh,pty"]

CMD ["sh", "-c", "socat TCP-LISTEN:5000,reuseaddr,fork EXEC:'/run.sh'"]