FROM ubuntu:18.04

RUN dpkg --add-architecture i386

RUN apt-get update && apt-get install -y libc6:i386 gdbserver


COPY flag.txt /flag.txt

COPY libc-2.27.so /lib/custom_libc/libc.so.6

COPY betstar5000 /server

RUN chmod +x /server /lib/custom_libc/libc.so.6

EXPOSE 5000

CMD ["gdbserver", ":5000", "./server"]